site_name: Formatura Licenciatura em Matemática EaD CETEC/UFRB
site_url: https://disponha.org
site_description: 'A web reference of common baseball statistics.'
copyright: '&copy; 2019 Superintendência de Educação Aberta e a Distância - SEAD/UFRB.'
google_analytics:
    - 'UA-107693948-1'
    - 'auto'
site_author: Carlos André
edit_uri: ''
pages:
    - Home: index.md
    - Convite:
        - 'Identificação': identificacao.md
        - 'Nome da Turma': nome-turma.md
        - 'Mensagem': mensagem.md
        - 'Agradecimentos': agradecimentos.md
        - 'Formandos Pólo Ipirá ': formandos-polo-ipira.md
        - 'Formandos Pólo Macaúbas': formandos-polo-macaubas.md
        - 'Formandos Pólo Rio Real': formandos-polo-rio-real.md
        - 'Formandos Pólo Vitória da Conquista': formandos-polo-vitoria-da-conquista.md
        - 'Mensagem Comissão': mensagem-comissao.md
theme:
  name: 'material'
  language: 'pt'
  logo: img/logo.png
  palette:
        primary: 'Indigo'
        accent: 'Indigo'
  feature:
    tabs: true
extra_javascript:
  - 'javascripts/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
site_dir: build
